alias mercy="kill -9 %1"
alias be="bundle exec"
alias r="bundle exec rails"
alias -g yo=' && echo dawg'
alias re="touch tmp/restart.txt"
alias hooray="echo \"Hooray! =D\""
alias superpush="git fetch && git rebase origin/master && git push"
alias hbs="hub browse"
alias gdmb="git branch --merged | grep -v \"\\*\" | xargs -n 1 git branch -d"
alias ack="ack-grep"
alias ls="ls -h --color=auto"

alias zs="zeus start"
alias zr="zeus rspec"
alias zv="zeus server"
alias zc="zeus console"
alias zg="zeus generate"
alias zk="zeus rake"
alias zkt="zeus rake -T"
